{{- if ne .Values.browserNamespace .Release.Namespace }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.browserNamespace }}
  labels:
    app.kubernetes.io/managed-by: bbroker
{{- end }}
